config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    member do
      post :add_new_batch
      get :new_batch_form
    end
  end
  resources :batches do
    resources :sections, only: [:new, :create]
  end
  resources :sections, only: [:edit, :update, :destroy]
  resources :departments do
    member do
      get :department_employees
      get :department_courses
    end
  end
  resources :employees
  resources :subjects
  get 'home/index'
  root "home#index"
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :department
  validates :first_name, :last_name, :date_of_joining, :email, :designation, :mobile, :about, presence: true
  validates :email, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :date_of_joining, :designation, :mobile, :about, :department_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6 col-sm-7 col-xs-12">

    <div class="form-group">
      <%= f.text_field :first_name, class: "form-control input-lg", placeholder: "First Name" %>
    </div>

    <div class="form-group">
      <%= f.text_field :last_name, class: "form-control input-lg", placeholder: "Last Name" %>
    </div>

    <div class="form-group">
      <%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
    </div>

    <div class="form-group">
      <%= f.date_select :date_of_joining, class: "form-control input-lg datepicker", placeholder: "Date of Joining" %>
    </div>

    <div class="form-group">
      <%= f.text_field :designation, class: "form-control input-lg", placeholder: "Employee Designation" %>
    </div>

    <div class="form-group">
      <%= f.text_field :mobile, class: "form-control input-lg", placeholder: "Modile Number" %>
    </div>

  </div>
  <div class="col-md-6 col-sm-5 col-xs-12">

    <div class="form-group">
      <%= f.select :department_id, options_for_select(Department.all.collect {|p| [ p.name, p.id ] },(f.object.try(:department_id))),{include_blank: 'Select Department'}, { :class => 'form-control input-lg'} %>
    </div>

    <div class="form-group">
      <%= f.text_area :about, class: "form-control input-lg about-emp", placeholder: "About Employee" %>
    </div>
  </div>

  <div class="col-md-6 col-xs-12 col-sm-7 col-lg-6">
    <div class="form-group actions">
      <%= f.submit class: "btn btn-lg btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="jumbotron">
    <h1>Listing Employees</h1>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-bordered dt-responsive nowrap" id="employee">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Date of joining</th>
          <th>Department</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @employees.each do |employee| %>
          <tr>
            <td><%= employee.full_name %></td>
            <td><%= employee.email %></td>
            <td><%= employee.date_of_joining %></td>
            <td><%= employee.department.try(:nickname) %></td>
            <td>
              <%= link_to 'Show', employee %><span></span>
              <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %><span></span>
              <%= link_to 'Edit', edit_employee_path(employee) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Employee', new_employee_path %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#employee').DataTable();
  });
</script>

app/views/employees/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>New Employee</h2>
  </div>
  <%= render 'form' %>
  <div class="col-md-6 col-xs-12 col-sm-5 col-lg-6">
    <div class="form-group">
      <%= link_to 'Back', employees_path, class: "btn btn-lg btn-primary btn-block" %>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Date of joining:</strong>
  <%= @employee.date_of_joining %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @employee.designation %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @employee.mobile %>
</p>

<p>
  <strong>About:</strong>
  <%= @employee.about %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>