config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    member do
      post :add_new_batch
      get :new_batch_form
    end
  end
  resources :batches do
    resources :sections, only: [:new, :create]
  end
  resources :sections, only: [:edit, :update, :destroy]
  resources :departments do
    member do
      get :department_employees
      get :department_courses
    end
  end
  resources :employees
  resources :subjects
  get 'home/index'
  root "home#index"
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :employees
  has_many :courses
  validates :name, :nickname, presence: true, uniqueness: true
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy, :department_employees, :department_courses]

  def index
    @search = Department.search(params[:q])
    @departments = @search.result
  end

  def show
  end

  def new
    @department = Department.new
  end

  def edit
  end

  def create
    @department = Department.new(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @department }
      else
        format.js
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @department }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @department.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def department_employees
    @employees = @department.employees
  end

  def department_courses
    @employees = @department.courses
  end

  private

    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name, :nickname)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<tr id="department_<%= department.id%>">
  <td><%= department.name %></td>
  <td><%= department.nickname %></td>
  <td><%= link_to 'Show', department, class: "btn btn-info" %></td>
  <td><%= link_to 'Edit', edit_department_path(department), :remote => true, class: "btn btn-warning" %></td>
  <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-danger" %></td>
</tr>

app/views/departments/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Edit Department</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/departments/_error.html.erb
<h4><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h4>
<ul>
<% @department.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>

app/views/departments/_form.html.erb
<%= form_for @department, :remote => true do |f| %>
  <div class="modal-body">
    <div class="error_explanation">
    </div>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control input-lg" %>
    </div>
    <div class="field">
      <%= f.label :nickname %>
      <%= f.text_field :nickname, class: "form-control input-lg" %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">Close</button>
    <%= f.submit "Save Department", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/departments/_new.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">New Department</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/departments/create.js.erb
<% if @department.errors.any? %>
  $(".error_explanation").html("<%= escape_javascript(render('departments/error'))%>")
<% else %>
  $("#department-modal").modal('hide')
  $("#department-index").append("<%= escape_javascript(render('department', department: @department )) %>")
<% end %>

app/views/departments/department_courses.html.erb
<div class="container">
  <div class="text-center">
    <div class="well">
      <h2><%= @department.nickname %> Courses</h2>
    </div>
  </div>
  <div class="">
  </div>
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <% @department.courses.each do |course| %>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading_<%= course.id%>">
          <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse_<%= course.id%>" aria-expanded="true" aria-controls="collapseOne">
              <%= course.name %>
            </a>
          </h4>
        </div>
        <div id="collapse_<%= course.id%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_<%= course.id%>">
          <div class="panel-body">
            <table class="table">
              <tbody>
                <% course.batches.each do |batch| %>
                  <tr>
                    <td><%= link_to "#{batch.course.name} #{batch.start_year.strftime('%Y')} - #{batch.end_year.strftime('%Y')}",batch %></td>
                    <td>
                      <%= link_to edit_batch_path(batch), class: "btn btn-warning", remote: true do %>
                        <i class="fa fa-pencil"></i> Edit
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <center>
    <div class="btm-sec">
      <a href="<%= department_path(@department) %>" class="back-link">
        <%= image_tag "bkbtn.png", class: "img-responsive"%>
      </a>
    </div>
  </center>
</div>

app/views/departments/department_employees.html.erb
<div class="container">
  <div class="table-responsive">
    <table class="table table-striped">
      <thead class="dept-emp-table">
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Email</th>
          <th>Joining Date</th>
          <th>Info</th>
        </tr>
      </thead>
      <tbody class="dept-emp-table">
        <% @employees.each do |employee| %>
         <tr>
            <td><%= image_tag "k2.jpg", class: "dept-emp"%></td>
            <td><%= employee.full_name %></td>
            <td><%= employee.email %></td>
            <td><%= employee.date_of_joining %></td>
            <td>
              <%= link_to 'Go', employee, class: "btn btn-info" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <center>
    <div class="btm-sec">
      <a href="<%= department_path(@department) %>" class="back-link">
        <%= image_tag "bkbtn.png", class: "img-responsive"%>
      </a>
    </div>
  </center>
</div>

app/views/departments/destroy.js.erb
$("#department_<%= @department.id%>").remove();

app/views/departments/edit.js.erb
$("#edit-department-modal").html("<%= escape_javascript(render 'edit') %>")
$("#edit-department-modal").modal('show')

app/views/departments/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="jumbotron">
    <h3>Listing Departments</h3>
  </div>
  <div class="search_form">
    <%= search_form_for @search do |f| %>
      <div class="input-group">
        <%= f.text_field :name_or_nickname_cont, :placeholder => "Search Department", class: "form-control" %>
        <span class="input-group-btn">
          <%= f.submit "Search", class: "btn btn-primary" %>
        </span>
      </div>
    <% end %>
  </div>
  <div class="table table-responsive">
  <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Nickname</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody id="department-index">
        <% @departments.each do |department| %>
          <tr id="department_<%= department.id%>">
            <td><%= department.name %></td>
            <td><%= department.nickname %></td>
            <td><%= link_to 'Show', department, class: "btn btn-info" %></td>
            <td><%= link_to 'Edit', edit_department_path(department), :remote => true, class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Department', new_department_path, :remote => true, class: "btn btn-primary" %>

</div>
<div class="modal fade" id="department-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>
<div class="modal fade" id="edit-department-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

app/views/departments/new.js.erb
$("#department-modal").html("<%= escape_javascript(render 'new') %>")
$("#department-modal").modal('show')

app/views/departments/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="jumbotron">
    <div class="text-center">
      <h2><%= @department.name %></h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-sm-4 col-xs-12 col-lg-4">
      <a href="<%= department_courses_department_path(@department.id)%>" class="dept-item-link">
        <div class="department-items">
          <%= image_tag "courses.jpg", class: "img-responsive" %>
          <div class="item-heading text-center">
            <h3>Courses Offered</h3>
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12 col-lg-4">
      <a href="<%= department_employees_department_path(@department.id)%>" class="dept-item-link">
        <div class="department-items">
          <%= image_tag "employees.png", class: "img-responsive" %>
          <div class="item-heading text-center">
            <h3>Employees</h3>
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12 col-lg-4">
      <a href="" class="dept-item-link">
        <div class="department-items">
          <%= image_tag "students.png", class: "img-responsive" %>
          <div class="item-heading text-center">
            <h3>Students</h3>
          </div>
        </div>
      </a>
    </div>
  </div>
  <center>
    <div class="btm-sec">
      <a href="<%= departments_path %>" class="back-link">
        <%= image_tag "bkbtn.png", class: "img-responsive"%>
      </a>
    </div>
  </center>
</div>

app/views/departments/update.js.erb
<% if @department.errors.any? %>
  $(".error_explanation").html("<%= escape_javascript(render('departments/error'))%>")
<% else %>
  $("#edit-department-modal").modal('hide')
  $('#department_<%= @department.id %>').replaceWith("<%= escape_javascript(render('department', department: @department )) %>")
<% end %>