config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    member do
      post :add_new_batch
      get :new_batch_form
    end
  end
  resources :batches do
    resources :sections, only: [:new, :create]
  end
  resources :sections, only: [:edit, :update, :destroy]
  resources :departments do
    member do
      get :department_employees
      get :department_courses
    end
  end
  resources :employees
  resources :subjects
  get 'home/index'
  root "home#index"
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  belongs_to :batch
  has_many :attachments, as: :attachable
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  def section_name
    "#{self.batch.course.name} #{self.name} #{self.begining.strftime('%b')} #{self.begining.strftime('%Y')} - #{self.closing.strftime('%b')} #{self.closing.strftime('%Y')}"
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:edit, :update, :destroy]
  before_action :set_batch, only: [:new, :create]

  def index
    @sections = Section.all
  end

  def show
  end

  def new
    @batch.sections.build
  end

  def edit
  end

  def create
    @section = @batch.sections.create(section_params)
    respond_to do |format|
      if @section.save
        format.js
      else
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @section.update(section_params)
        format.js
      else
        format.js
      end
    end
  end

  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_section
      @section = Section.find(params[:id])
    end

    def section_params
      params.require(:section).permit(:name, :begining, :closing, :status)
    end

    def set_batch
      @batch = Batch.find(params[:batch_id])
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_attachment_fields.html.erb
<div class="nested-fields">
  <%= f.file_field :attachment %>
  <%= link_to_remove_association "remove attachment", f%>
</div>

app/views/sections/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Edit Section</h4>
    </div>
    <%= form_for @section, remote: true do |f| %>
      <div class="modal-body">
        <div class="error_explanation">
        </div>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.text_field :status, class: "form-control"%>
        </div>
        <div class="form-group date-sel">
          <%= f.date_select :begining%>
        </div>
        <div class="form-group date-sel">
          <%= f.date_select :closing%>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-lg btn-default hidden-xs" data-dismiss="modal">Close</button>
        <%= f.submit class: "btn btn-lg btn-custom hidden-xs" %>
        <%= f.submit class: "btn btn-lg btn-custom btn-block visible-xs" %>
      </div>
    <% end %>
  </div>
</div>

app/views/sections/_error.html.erb
<h4><%= pluralize(@section.errors.count, "error") %> prohibited this course from being saved:</h4>
<ul>
  <% @section.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

app/views/sections/_form.html.erb
<%= form_for ([@batch, @batch.sections.build]), {role: "form", remote: true}  do |f| %>
  <div class="modal-body">
    <div class="error_explanation">
    </div>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.text_field :status, class: "form-control"%>
    </div>
    <div class="form-group date-sel">
      <%= f.date_select :begining%>
    </div>
    <div class="form-group date-sel">
      <%= f.date_select :closing%>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-lg btn-default hidden-xs" data-dismiss="modal">Close</button>
    <%= f.submit class: "btn btn-lg btn-custom hidden-xs" %>
    <%= f.submit class: "btn btn-lg btn-custom btn-block visible-xs" %>
  </div>
<% end %>

app/views/sections/_new.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">New Section</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/sections/_section.html.erb
<tr id="section_<%= section.id%>">
  <td><%= section.section_name %></td>
  <td><%= section.status %></td>
  <td class="hidden-xs">
    <%= link_to edit_section_path(section), class: "btn btn-warning" do %>
      <i class="fa fa-pencil"></i> Edit
    <% end %>
  </td>
  <td class="visible-xs">
    <%= link_to edit_section_path(section), class: "btn btn-warning btn-xs" do %>
      <i class="fa fa-pencil"></i> Edit
    <% end %>
  </td>
</tr>

app/views/sections/create.js.erb
<% if @section.errors.any? %>
  $(".error_explanation").html("<%= escape_javascript(render('error'))%>")
<% else %>
  $("#new-section-modal").modal('hide')
  $("#section-index").append("<%= escape_javascript(render('section', section: @section )) %>")
<% end %>

app/views/sections/edit.js.erb
$("#edit-section-modal").html("<%= escape_javascript(render 'edit') %>")
$("#edit-section-modal").modal('show')

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= section.course.try(:name) %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.js.erb
$("#new-section-modal").html("<%= escape_javascript(render 'new') %>")
$("#new-section-modal").modal('show')

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @section.course_id %>
</p>

<% @section.attachments.each do |attachment| %>
  <%= link_to "Download This PDF", attachment.attachment_url %><br>
<% end %>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>

app/views/sections/update.js.erb
<% if @section.errors.any? %>
  $(".error_explanation").html("<%= escape_javascript(render('error'))%>")
<% else %>
  $("#edit-section-modal").modal('hide')
  $('#section_<%= @section.id %>').replaceWith("<%= escape_javascript(render('section', section: @section )) %>")
<% end %>