config/routes.rb
Rails.application.routes.draw do

  resources :courses do
    member do
      post :add_new_batch
      get :new_batch_form
    end
  end
  resources :batches do
    resources :sections, only: [:new, :create]
  end
  resources :sections, only: [:edit, :update, :destroy]
  resources :departments do
    member do
      get :department_employees
      get :department_courses
    end
  end
  resources :employees
  resources :subjects
  get 'home/index'
  root "home#index"
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  def index
    @search = Subject.search(params[:q])
    @subjects = @search.result
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @subject }
      else
        format.js
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @subject }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private

    def set_subject
      @subject = Subject.find(params[:id])
    end

    def subject_params
      params.require(:subject).permit(:name, :nickname)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Edit Subject</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/subjects/_error.html.erb
<h4><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h4>
<ul>
<% @subject.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>

app/views/subjects/_form.html.erb
<%= form_for @subject, :remote => true do |f| %>
  <div class="modal-body">
    <div class="error_explanation">
    </div>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control input-lg" %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">Close</button>
    <%= f.submit "Save Subject", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/subjects/_new.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">New Subject</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/subjects/_subject.html.erb
<tr id="subject_<%= subject.id %>">
  <td><%= subject.name %></td>
  <td><%= subject.nickname %></td>
  <td><%= link_to 'Show', subject, class: "btn btn-info" %></td>
  <td><%= link_to 'Edit', edit_subject_path(subject), :remote => true, class: "btn btn-warning" %></td>
  <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-danger" %></td>
</tr>

app/views/subjects/create.js.erb
<% if @subject.errors.any? %>
  $(".error_explanation").html("<%= escape_javascript(render('subjects/error'))%>")
<% else %>
  $("#subject-modal").modal('hide')
  $("#subject-index").append("<%= escape_javascript(render('subject', subject: @subject )) %>")
<% end %>

app/views/subjects/destroy.js.erb
$("#subject_<%= @subject.id%>").remove();

app/views/subjects/edit.js.erb
$("#edit-subject-modal").html("<%= escape_javascript(render 'edit') %>")
$("#edit-subject-modal").modal('show')

app/views/subjects/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="jumbotron">
    <h1>Listing Subjects</h1>
  </div>
  <div class="search_form">
    <%= search_form_for @search do |f| %>
      <div class="input-group">
        <%= f.text_field :name_or_nickname_cont, :placeholder => "Search Subjects", class: "form-control" %>
        <span class="input-group-btn">
          <%= f.submit "Search", class: "btn btn-primary" %>
        </span>
      </div>
    <% end %>
  </div>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Nickname</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody id="subject-index">
        <% @subjects.each do |subject| %>
          <tr id="subject_<%= subject.id %>">
            <td><%= subject.name %></td>
            <td><%= subject.nickname %></td>
            <td><%= link_to 'Show', subject, class: "btn btn-info" %></td>
            <td><%= link_to 'Edit', edit_subject_path(subject), :remote => true, class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Subject', new_subject_path, class: "btn btn-primary", remote: true %>
</div>
<div class="modal fade" id="subject-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>
<div class="modal fade" id="edit-subject-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

app/views/subjects/new.js.erb
$("#subject-modal").html("<%= escape_javascript(render 'new') %>")
$("#subject-modal").modal('show')

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/update.js.erb
<% if @subject.errors.any? %>
  $(".error_explanation").html("<%= escape_javascript(render('subjects/error'))%>")
<% else %>
$("#edit-subject-modal").modal('hide')
$('#subject_<%= @subject.id %>').replaceWith("<%= escape_javascript(render('subject', subject: @subject )) %>")
<% end %>